baseURL = 'https://sethdoty.dev/'
languageCode = 'en-us'
title = 'Seth Doty'
theme = 'ananke'
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe = true

[params]
text_color = ""
author = "Seth Doty"
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "bluesky",
  "linkedin",
  "rss"
]

[params.ananke.social.linkedin]
username = "sethdoty"
profilelink = "www.linkedin.com/in/sethdoty"

[params.ananke_social.bluesky]
name = "bluesky"
url = "https://bsky.app/profile/sethdoty.bsky.social"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/About'
    weight = 20
